Controllers/AccessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using proyecto_MVC.Models; 

namespace proyecto_MVC.Controllers
{
    public class AccessController : Controller
    {
        // GET: Access
        public ActionResult Index()
        { 
            return View();
        }
        public ActionResult Enter(string user, string password)
        {
            try
            {
                using (BD_MVCEntities db = new BD_MVCEntities())
                {
                    var lst = from d in db.tbl_user   //Recrea el lenguaje sql
                              where d.email == user && d.password == password && d.idState==1
                              select d;
                    if (lst.Count() > 0)
                    {
                        tbl_user oUser = lst.First();
                        Session["User"] = oUser;
                        return Content("Acceso Conecedido");

                    }else
                    {
                        return Content("Usuario Invalido");
                    }

                              }
                return Content("1");
            }
            catch(Exception ex)
            {
                return Content("Ocurrio un error :(" + ex.Message);
            }
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using proyecto_MVC.Models;
using proyecto_MVC.Models.tableViewModels;
using proyecto_MVC.Models.ViewModels;


namespace proyecto_MVC.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            List<UserTableViewModel> lst = null;
            using(BD_MVCEntities db=  new BD_MVCEntities())
            {
                lst = (from d in db.tbl_user
                       where d.idState == 1
                       orderby d.email
                       select new UserTableViewModel
                       {
                           Email = d.email,
                           Id = d.Id_usuario,
                           Edad = d.edad
                       }).ToList();
            }

            return View(lst);
        }
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]// Me sirve para hacer que este metodo solo entre por POST
        public ActionResult Add(UserViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            using (var db = new BD_MVCEntities())
            {
                tbl_user oUser = new tbl_user();
                oUser.idState = 1;
                oUser.email = model.Email;
                oUser.edad = model.Edad;
                oUser.password = model.Password;

                db.tbl_user.Add(oUser);

                db.SaveChanges();

            }

            return Redirect(Url.Content("~/User/"));

        }


        public ActionResult Edit(int Id)
        {
            EditUserViewModel model = new EditUserViewModel();

            using (var db = new BD_MVCEntities())
            {
               var oUser = db.tbl_user.Find(Id);
                model.Edad = (int)oUser.edad;
                model.Email = oUser.email;
                model.Id = oUser.Id_usuario;
            }


            return View(model);
        }

        [HttpPost]// Me sirve para hacer que este metodo solo entre por POST
        public ActionResult Edit(EditUserViewModel model)

        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var db = new BD_MVCEntities())
            {
               var oUser = db.tbl_user.Find(model.Id);
                oUser.email = model.Email;
                oUser.edad = model.Edad;

                if(model.Password !=null && model.Password.Trim() != "")
                {
                    oUser.password = model.Password; // Si se cambia el password o si queda el que ya estaba
                }
                db.Entry(oUser).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }

            return Redirect(Url.Content("~/User/"));

        }



    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar "></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Proyecto  MVC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand logo" })
            </div>
            <div class="navbar-collapse collapse ">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li> @*Pone un inico va al Controler home al accion index*@
                    <li>@Html.ActionLink("Usuario", "Index", "User")</li>
                    <li>@Html.ActionLink("Cerrar Sesion", "LogOff   ", "Access")</li> 
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content ">
        
        @RenderBody()
    
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/javaScript")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutLogin.cshtml
@{
    ViewBag.Title = "_LayoutLogin";
}


<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
 
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar "></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Protecto MVC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand logo" })
            </div>

        </div>
    </div>
    <div class="container body-content">

        @RenderBody()

        <hr />
        <footer class="footer">
            <p>&copy;  @DateTime.Now.Year - Proyecto MVC ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/javaScript")
    @RenderSection("scripts", required: false)
</body>
</html>